# Numpy

- Numerical Python

- Numpy arrays are like python's built in list type, but NumPy arrays provide much more effiecient storage and data operations as the array grow larger than in size.



### Day 1: Introduction to NumPy
- What is NumPy?

    - Fundamental package for scientific computing in Python.

    - Provides high-performance multidimensional arrays.

    - Efficient operations over large datasets.

In [2]:
! pip install numpy

In [1]:
import numpy
numpy.__version__

'1.21.6'

### Day 2: Creating Arrays

#### 1. Using np.array()

In [4]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


### 2. Create arrays with ranges:

In [6]:
# np.arange(start, stop, step)

arr = np.arange(0, 10, 2)  # [0 2 4 6 8]

arr

array([0, 2, 4, 6, 8])

In [ ]:
import numpy as np

L = list(range(10))
print(L)

type(L[0])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


int

In [11]:
L2 = [str(c) for c in L]

print(L2)

type(L2[0])

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


str

In [ ]:
# because of Python's dynamic typing, we can create heterogeneous list:

L3 = [True, '2',3.0, 4]

print([type(item) for item in L3])

[type(item) for item in L3]

[<class 'bool'>, <class 'str'>, <class 'float'>, <class 'int'>]


[bool, str, float, int]

In [ ]:
# Fixed type arrys in Python

import array
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# np.linspace(start, stop, num_points)

arr = np.linspace(0, 1, 5)  # [0.   0.25 0.5  0.75 1. ]

arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
# Zeros, Ones, Identity Matrix


a1 = np.zeros((2,3))    # 2x3 matrix of zeros
print('\n 2x3 matrix of zeros \n', a1)

a2 = np.ones((3,3))     # 3x3 matrix of ones
print('\n 3x3 matrix of ones \n',a2)

a3 = np.eye(4)          # 4x4 Identity Matrix
print('\n 4x4 Identity Matrix \n',a3)


 2x3 matrix of zeros 
 [[0. 0. 0.]
 [0. 0. 0.]]

 3x3 matrix of ones 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 4x4 Identity Matrix 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Day 3: Array Attributes
Explore the properties of arrays:

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)     # Number of dimensions
print(arr.shape)    # Shape of the array (rows, columns)
print(arr.size)     # Total number of elements
print(arr.dtype)    # Data type of elements
print(arr.itemsize) # Bytes per element


2
(2, 3)
6
int32
4


In [32]:
# Multidimensional arrays with nested lists result

np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [33]:
# create a length 10 integer array filled with zeros

np.zeros(10, dtype=int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
# create an 3*5 floating point array filled with 1s

np.ones(shape=(3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
# create a 3*5 array filled with 3.14

np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [37]:
# create an array filled with a linear sequence
# Starting at 0 and ending at 20, stepping by 2
# this is similar to the built in function range() functional
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
# create a 3*3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3,3))

array([[0.32343542, 0.1770081 , 0.45087338],
       [0.20896014, 0.20555683, 0.80591409],
       [0.06883269, 0.48487985, 0.54277265]])

In [40]:
# create a 3*3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[-1.01406559,  1.6355486 , -0.80693774],
       [-0.86813844, -1.14755784, -0.94136271],
       [ 1.31615511,  0.16105372,  0.33670563]])

In [41]:
# create a 3*3 array of  random integers in the interval [0,10)
np.random.randint(0,10,(3,3))


array([[6, 6, 4],
       [6, 8, 8],
       [2, 7, 8]])

In [43]:
# create an indentity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
# Create an uninitialized array of three integers
# the values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])